export { Header } from './header'
export { Hero } from './hero'
export { Features } from './features'
export { Pricing } from './pricing'
export { Comparison } from './comparison'
export { FAQ } from './faq'
export { CTA } from './cta'
export { Footer } from './footer'
